### PR TITLE
Ls bandcards

### PR DESCRIPTION
**Pull request by lolasimp**

### CODE REVIEW

**Comment by awieckert** [comment]
👎

**Comment by colinlwhite** [comment]
Good to go!

**Comment by jessrod11** [comment]
*Colin/Bassist
*Stix/Guitarist
*Adam- Lead Vocalist
Lola- Key-tar

**Comment by jessrod11** [comment]
👍

**Comment by leotaylor** [comment]
👍

**Comment by colinlwhite** [comment]
Good to go!

**Pull request merged**
