### PR TITLE
Added background image to IMG directory. Added main-container to all …

### PR DESCRIPTION
**Pull request by awieckert**
…pages expect Home page. Added background image to all pages expect Home Page. Added animations to albums on media page and added black font color to second album.

### CODE REVIEW

**Comment by colinlwhite** [comment]
Good to go!

**Comment by jessrod11** [comment]
👍

**Comment by lolasimp** [comment]
👍

**Comment by colinlwhite** [comment]
Good to go again!

**Comment by leotaylor** [comment]
👍

**Pull request merged**
