### PR TITLE
Ajw tour page fix

### PR DESCRIPTION
**Pull request by awieckert**

### CODE REVIEW

**Comment by leotaylor** [comment]
👍 looks good. Top Padding?

**Comment by jessrod11** [comment]
awesome!! height with a vh unit! You taught me something new with that one! 👍

**Comment by colinlwhite** [comment]
Wow, looks great! Thanks man and good to go!

**Comment by awieckert** [comment]
Thanks guys, and thank google not me lol Found it on the inter-webs!

**Pull request merged**
